[env]
platform = espressif8266
board = nodemcuv2
framework = arduino

monitor_speed = 115200
build_flags = -I include
test_framework = unity

lib_deps =
    https://github.com/bogde/HX711.git
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    adafruit/RTClib @ ^2.1.1
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.5
    ricmoo/QRCode@^0.0.1
    SPI
    Wire

extra_scripts = pre:scripts/inject_secrets.py


[env:nodemcuv2-usb]
extends = env
upload_protocol = esptool
upload_port = COM10
monitor_port = COM10


[env:nodemcuv2-ota]
extends = env

upload_protocol = espota
upload_port = 192.168.1.102